### ISSUE TITLE
About gait controller training

### ISSUE THREAD

**Issue by gaiyi7788** [UT-Austin-RPL/PRELUDE#2]
Hello,
     Thanks a lot for providing this useful code. I'm interesting about this work and tried to train the gait controller at the first time. However, I was unable to obtain a converged training result. The training visualization is shown below. The config file used is the default gait config.

![image](https://user-images.githubusercontent.com/56317459/232178748-6f5bc7ec-3670-48b7-94cc-66bbefa48470.png)

Could you give me some advice! Thank you!

**Comment by kiwi-sherbet** [comment]
I would be happy to help you with it.

The default gait config may be different from the config I used for training the Gait Controller. It seems to fail while exploring data at the beginning. Can you try either increase `Step/Epoch` or change Initial Sigma at `config/ppo.yaml`?

**Comment by kiwi-sherbet** [comment]
I would be happy to help you with it.

The default gait config may be different from the config I used for training the Gait Controller. It seems to fail while exploring data at the beginning. Can you try either increase `Step/Epoch` or change `Initial Sigma` at `config/ppo.yaml`?

**Comment by gaiyi7788** [comment]
Thanks a lot for your timely reply!

I made a few more attempts. I was training on my own laptop before and now I rent a cloud computing server for training and get a relatively good result. 

![image](https://user-images.githubusercontent.com/56317459/232197368-18750dcb-4d54-4439-b68a-f18f9980d934.png)

Maybe there is something different for the different training environment. My laptop's CPU is Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz and GPU is 1050ti. I will modify the configuration file and try more. 

One more question is that I would like to know how much best_reward your training can reach at convergence, and how many epochs were performed.

Thank you for your friendly advice!

**Comment by kiwi-sherbet** [comment]
Converging reward values vary across coefficients of the reward terms. I usually spent a half day on my GPU desktop with Ryzen 5900X + RTX 3070  (about 2-4M steps).

**Comment by gaiyi7788** [comment]
Thank you very much for your patient answers! Good luck with your research!
