### ISSUE TITLE
Issue with Training Gait Policy

### ISSUE THREAD

**Issue by jyrana** [UT-Austin-RPL/PRELUDE#3]
Tianshou 0.4.1 does not have save_checkpoint_fn. it's available from 0.4.2.

While running training_gait it's throwing error, 
 train(save_path, os.path.join(PATH_CONFIG, args.config))
  File "/home/PRELUDE/scripts/train_gait.py", line 239, in train
    result = onpolicy_trainer(
  File "/home/.local/lib/python3.10/site-packages/tianshou/trainer/onpolicy.py", line 124, in onpolicy_trainer
    logger.log_train_data(result, env_step)
  File "/home/jpr8961/PRELUDE/scripts/gait/logger.py", line 77, in log_train_data
for key, value in collect_result["infos"].items():
KeyError: 'infos'

I checked the file Tianshou/data/collector.py and it doesn't have the anything related to 'infos' .

**Comment by kiwi-sherbet** [comment]
This seems an issue on Tianshou's versions. There may be two temporal solutions you can try immediately.
1. You can explicitly add the 'infos' key in Tianshou. 
 - Add `"infos": copy.copy(self.data.info),` [here](https://github.com/thu-ml/tianshou/blob/dd4a01132cbb7fd70b2906619a05b187c91a41a7/tianshou/data/collector.py#L301)
 -  Add `"infos": copy.copy(whole_data.info),` [here](https://github.com/thu-ml/tianshou/blob/dd4a01132cbb7fd70b2906619a05b187c91a41a7/tianshou/data/collector.py#L503).
2. Remove the lines for logging `infos` at these lines [[1](https://github.com/UT-Austin-RPL/PRELUDE/blob/249dc892c5781d88454c9544d73f6912d1dee4ac/scripts/gait/logger.py#L76), [2](https://github.com/UT-Austin-RPL/PRELUDE/blob/249dc892c5781d88454c9544d73f6912d1dee4ac/scripts/gait/logger.py#L105)].

I hope these would be helpful.
