### ISSUE TITLE
Gait Policy Gui Issue

### ISSUE THREAD

**Issue by nfhe1** [UT-Austin-RPL/PRELUDE#4]
Thank you very much for your awesome contribution.
I have a problem choosing 'gait' now.

![1695028326(1)](https://github.com/UT-Austin-RPL/PRELUDE/assets/111717815/2e0a9929-cc1a-43d3-ba32-cbc27ab5b922).

Could you give me some advice! Thank you!

**Comment by nfhe1** [comment]
I have opened the render in the code, and every training screen is stationary, and the screen remains grayish white throughout the training process. How can I retrieve the data for each frame？

Looking forward to your reply

**Comment by kiwi-sherbet** [comment]
Thank you for your interest in our project.

We are using a distributed PPO algorithm, so we need to run multiple PyBullet environments parallelly. Unfortunately, a PyBullet GUI server does not work when multiple physics simulations are running. Therefore, you would need to record videos to monitor training progress, not using a GUI. I hope this will help.

**Comment by nfhe1** [comment]
Thank you very much for your reply.

I have seen the excellent answer you provided here, and I have solved this problem. Therefore, I will close this issue.

Thank you again.
